# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build lifi`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t lifi`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system lifi && \
          adduser --system -G lifi lifi

COPY dist/lifi lifi
RUN chown -R lifi:lifi .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix lifi --omit=dev -f install

CMD [ "node", "lifi" ]
